server {
    listen 5001;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        
        # CORS headers pour Module Federation
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    }

    # Cache Control pour remoteEntry.js
    location ~* \.js$ {
        root /usr/share/nginx/html;
        add_header 'Access-Control-Allow-Origin' '*';
        expires 1y;
        add_header Cache-Control "public, no-cache";
    }
}
